require("dotenv").config();
const path=require("path");
const express=require("express");
const http=require("http");
const {Server}=require("socket.io");
const app=express();
const server=http.createServer(app);
const io=new Server(server);
const PORT=8001;
app.set("view engine","ejs");
app.set("views",path.resolve("./views"));
app.use(express.urlencoded({extended:false}));
const fileroutes=require("./routes/fileroutes");
app.use('/',fileroutes);
const chatroutes=require("./routes/chatroutes");
app.use('/',chatroutes);
const sockethandler=require("./socket/index");
sockethandler(io);
server.listen(PORT,()=> console.log(`server has started at PORT:8001`));